debug: false
deepspeed_config:
  deepspeed_config_file: configs/zero3.json
  deepspeed_multinode_launcher: standard
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
main_training_function: main
num_processes: 32
num_machines: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
